### ISSUE TITLE
Cannot get past welcome screen

### ISSUE THREAD

**Issue by rmsc** [ambrice/timesheet#5]
I just installed Timesheet through f-droid. When executing it I get the "Welcome to Timesheet!" screen, but can't get past that.

My phone (an OnePlus 2) doesn't have the "menu" hardware button, which I suspect is what I'm missing to start using the app.

**Comment by zacKolton** [comment]
Granted its been five years, you have to click the bottom right of the screen. The menu appears. Kind of a cool idea actually (opposed to the standard bottom menu)
